apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: doker-task-tp-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          command: ['flask', 'run', '--host=0.0.0.0', '--reload']
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: db-password
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: FLASK_ENV

          restartPolicy: Always # restart: on-failure → géré par K8s nativement

      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z database-service 3306; do
                echo "Waiting for database...";
                sleep 2;
              done

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
