apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: default
data:
  # Database
  MYSQL_DATABASE: 'application_db'
  MYSQL_USER: 'application_user'
  # Backend
  DB_HOST: 'database-service' # Nom du Service K8s de la BDD
  DB_NAME: 'taskdb'
  DB_USER: 'application_user'
  FLASK_ENV: 'development'
  # Frontend
  CHOKIDAR_USEPOLLING: 'true'
  VITE_API_URL: 'http://backend-service:5000'
